package main

// ─── WordPress-specific signatures ──────────────────────────────────────────

var WordPressSignatures = []SignatureDef{
	// ━━━ WP Backdoors / Webshells ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{"WP-BD-001", CRITICAL, "backdoor",
		"WordPress theme/plugin backdoor - eval of POST/GET data",
		`(?i)(?:eval|assert|system|exec)\s*\(\s*(?:base64_decode\s*\(\s*)?\$_(?:POST|GET|REQUEST|COOKIE)`,
		[]string{".php"}},
	{"WP-BD-002", CRITICAL, "backdoor",
		"Backdoor in wp-includes or wp-admin (core tampered)",
		`(?i)(?:eval|assert|system|passthru|shell_exec)\s*\(\s*(?:base64_decode|gzinflate|gzuncompress|str_rot13)\s*\(`,
		[]string{".php"}},
	{"WP-BD-003", HIGH, "backdoor",
		"Suspicious file_put_contents in uploads directory",
		`(?i)file_put_contents\s*\([\s\S]{0,200}(?:wp-content/uploads|wp-includes)`,
		[]string{".php"}},
	{"WP-BD-004", CRITICAL, "backdoor",
		"WordPress admin user injection via direct DB write",
		`(?is)INSERT\s+INTO\s+[\s\S]{0,50}(?:wp_users|wp_usermeta)[\s\S]{0,200}(?:administrator|wp_capabilities)`,
		[]string{".php"}},
	{"WP-BD-005", HIGH, "backdoor",
		"Rogue WordPress plugin with shell functionality",
		`(?is)Plugin\s+Name:[\s\S]{0,200}(?:eval|shell_exec|system|passthru|proc_open)\s*\(`,
		[]string{".php"}},

	// ━━━ WP Skimmers (WooCommerce) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{"WP-SK-001", CRITICAL, "skimmer",
		"WooCommerce checkout form data interception",
		`(?is)(?:woocommerce|wc-checkout|payment_method)[\s\S]{0,200}(?:addEventListener|onsubmit)[\s\S]{0,300}(?:fetch|XMLHttp|sendBeacon|new\s+Image)`,
		[]string{".js", ".php"}},
	{"WP-SK-002", CRITICAL, "skimmer",
		"WooCommerce payment gateway credential theft",
		`(?is)(?:wc_get_order|WC_Payment_Gateway|process_payment)[\s\S]{0,500}(?:curl_exec|wp_remote_post|file_get_contents\s*\(\s*['"]https?://)`,
		[]string{".php"}},

	// ━━━ WP-Specific Malware ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{"WP-MW-001", CRITICAL, "malware",
		"WordPress SEO spam / pharma hack injection",
		`(?is)(?:viagra|cialis|pharmacy|casino|poker|payday.?loan|buy.?cheap)[\s\S]{0,200}(?:display\s*:\s*none|visibility\s*:\s*hidden|position\s*:\s*absolute[\s\S]{0,50}left\s*:\s*-\d{4})`,
		[]string{".php", ".html"}},
	{"WP-MW-002", HIGH, "malware",
		"WordPress redirect malware via wp_redirect or header()",
		`(?i)(?:wp_redirect|header\s*\(\s*['"]Location)[\s\S]{0,100}\$_(?:GET|POST|SERVER|COOKIE)`,
		[]string{".php"}},
	{"WP-MW-003", HIGH, "malware",
		"Malicious WordPress cron event (wp_schedule_event abuse)",
		`(?is)wp_schedule_event[\s\S]{0,200}(?:eval|base64_decode|curl_exec|file_get_contents\s*\(\s*['"]https?://)`,
		[]string{".php"}},
	{"WP-MW-004", CRITICAL, "malware",
		"WordPress wp-config.php credential exfiltration",
		`(?is)(?:DB_NAME|DB_USER|DB_PASSWORD|AUTH_KEY|SECURE_AUTH_KEY)[\s\S]{0,300}(?:curl|wp_remote|file_get_contents|mail\s*\()`,
		[]string{".php"}},
	{"WP-MW-005", HIGH, "malware",
		"Suspicious WordPress REST API endpoint registration",
		`(?is)register_rest_route[\s\S]{0,200}(?:eval|system|exec|shell_exec|passthru|base64_decode)`,
		[]string{".php"}},
	{"WP-MW-006", HIGH, "malware",
		"WordPress xmlrpc.php abuse / amplification",
		`(?is)(?:xmlrpc|system\.multicall|pingback\.ping)[\s\S]{0,200}(?:flood|brute|attack|exploit)`,
		[]string{".php"}},

	// ━━━ WP File Anomalies ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{"WP-FA-002", HIGH, "suspicious",
		"Suspicious .htaccess rewrite in uploads directory",
		`(?i)(?:AddHandler|AddType)[\s\S]{0,50}(?:php|phtml|application/x-httpd)`,
		[]string{".htaccess"}},
}

var WordPressSuspiciousFilenames = []SuspiciousFilenameDef{
	{`(?i)wp-content/uploads/.+\.php$`, HIGH, "PHP file in uploads directory"},
	{`(?i)wp-content/uploads/.+\.phtml$`, HIGH, "PHTML file in uploads directory"},
	{`(?i)wp-includes/.+(?:shell|backdoor|hack|wso|c99)`, CRITICAL, "Known malware in wp-includes"},
	{`(?i)wp-content/plugins/.+/(?:shell|backdoor|hack|wso|c99)\.php$`, CRITICAL, "Known malware in plugins"},
	{`(?i)wp-content/(?:\.php|\.suspected)$`, HIGH, "Suspicious file in wp-content root"},
	{`(?i)(?:^|/)(?:wp-tmp|wp-feed|wp-vcd|class-wp-cache)\.php$`, CRITICAL, "Known WordPress malware filename"},
	{`(?i)(?:^|/)wp-content/mu-plugins/.+\.php$`, MEDIUM, "Must-use plugin (verify legitimacy)"},
}

// ─── WordPress CVEs ─────────────────────────────────────────────────────────

var WordPressCVEs = []CVEDef{
	// 2025
	{"6.7.1", "CVE-2025-39223", HIGH,
		"Stored XSS via block editor in WordPress core",
		"Upgrade to 6.7.2+"},
	// 2024
	{"6.5.4", "CVE-2024-6307", HIGH,
		"Stored XSS in HTML API (authenticated)",
		"Upgrade to 6.5.5+"},
	{"6.4.3", "CVE-2024-31210", HIGH,
		"Remote Code Execution via plugin/theme upload on Windows",
		"Upgrade to 6.4.4+"},
	{"6.3.3", "CVE-2024-28890", MEDIUM,
		"PHP Object Injection in core",
		"Upgrade to 6.4.4+"},
	// 2023
	{"6.3.1", "CVE-2023-39999", MEDIUM,
		"Contributor+ comment read via REST API",
		"Upgrade to 6.3.2+"},
	{"6.2.2", "CVE-2023-38000", HIGH,
		"Stored XSS via post meta in block themes (ACTIVELY EXPLOITED)",
		"Upgrade to 6.3.2+"},
	{"6.2", "CVE-2023-22622", MEDIUM,
		"Information disclosure via wp-mail.php",
		"Upgrade to 6.2.1+"},
	// 2022
	{"5.8.3", "CVE-2022-21661", HIGH,
		"SQL Injection via WP_Query",
		"Upgrade to 5.8.3+"},
	{"5.8.2", "CVE-2022-21662", MEDIUM,
		"Stored XSS via post slugs (author+)",
		"Upgrade to 5.8.3+"},
	{"5.8.2", "CVE-2022-21664", HIGH,
		"SQL Injection via WP_Meta_Query",
		"Upgrade to 5.8.3+"},
	// Older critical
	{"5.7.1", "CVE-2021-29447", HIGH,
		"XXE in media upload (authenticated) - information disclosure",
		"Upgrade to 5.7.2+"},
	{"5.4.1", "CVE-2020-11738", HIGH,
		"Stored XSS via block editor",
		"Upgrade to 5.4.2+"},
	{"5.0.0", "CVE-2019-8942", CRITICAL,
		"Remote Code Execution via crafted image (crop tool) - ACTIVELY EXPLOITED",
		"Upgrade to 5.0.1+ or apply patch"},
	{"4.9.8", "CVE-2019-8943", CRITICAL,
		"Path Traversal to RCE (ACTIVELY EXPLOITED)",
		"Upgrade to 5.0+"},
}

// ─── WordPress log patterns ─────────────────────────────────────────────────

var WordPressLogPatterns = []LogExploitPatternDef{
	{"WPLOG-001", HIGH, "log_exploit",
		"WordPress xmlrpc.php brute force / DDoS amplification",
		`(?i)POST\s+\S*xmlrpc\.php`,
		""},
	{"WPLOG-002", HIGH, "log_exploit",
		"WordPress login brute force (wp-login.php)",
		`(?i)POST\s+\S*wp-login\.php`,
		""},
	{"WPLOG-003", HIGH, "log_exploit",
		"Direct access to PHP file in uploads",
		`(?i)GET\s+\S*wp-content/uploads/\S*\.php`,
		""},
	{"WPLOG-004", HIGH, "log_exploit",
		"WordPress REST API user enumeration",
		`(?i)GET\s+\S*wp-json/wp/v2/users`,
		""},
	{"WPLOG-005", MEDIUM, "log_exploit",
		"WordPress author enumeration via ?author=",
		`(?i)GET\s+\S*\?author=\d`,
		""},
	{"WPLOG-006", HIGH, "log_exploit",
		"Attempt to access wp-config.php",
		`(?i)GET\s+\S*wp-config\.php`,
		""},
	{"WPLOG-007", CRITICAL, "log_exploit",
		"WordPress plugin/theme file upload exploit",
		`(?i)POST\s+\S*(?:plugin-install|theme-install|async-upload)\.php`,
		""},
}
